package remote

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/agentflare-ai/amux/internal/config"
	"github.com/agentflare-ai/amux/internal/paths"
	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

// ConfigureEmbeddedHub configures the embedded NATS server for the director.
// It sets up the Operator/System/Account hierarchy if needed and writes the config file.
func ConfigureEmbeddedHub(cfg *config.Config) error {
	if cfg.NATS.Mode != "embedded" {
		return nil
	}

	// 1. Ensure directories exist
	configDir, _ := paths.DefaultConfigDir()
	natsDir := filepath.Join(configDir, "nats")
	jsDir := paths.ExpandHome(cfg.NATS.JetStreamDir)

	if err := os.MkdirAll(natsDir, 0700); err != nil {
		return err
	}
	if err := os.MkdirAll(jsDir, 0700); err != nil {
		return err
	}

	// 2. Setup Auth (Operator, System, Amux Account)
	if err := setupNATSAuth(natsDir); err != nil {
		return fmt.Errorf("failed to setup nats auth: %w", err)
	}

	// 3. Generate NATS Config File
	// We point to the artifacts generated by setupNATSAuth
	operatorJWTPath := filepath.Join(natsDir, "operator.jwt")
	resolverDir := filepath.Join(natsDir, "resolver")
	
	// We need the System Account Public Key for the config
	sysAccKP, err := loadKeyPair(filepath.Join(natsDir, "keys", "system.nkey"))
	if err != nil {
		return fmt.Errorf("failed to load system account key: %w", err)
	}
	sysPub, _ := sysAccKP.PublicKey()

	natsConfigContent := fmt.Sprintf(`
server_name: amux-hub
listen: %s
operator: %s
system_account: %s

resolver {
    type: full
    dir: %s
    allow_delete: true
    interval: "2m"
}

jetstream {
    store_dir: %s
}

leafnodes {
    port: 7422
}
`, cfg.NATS.Listen, operatorJWTPath, sysPub, resolverDir, jsDir)

	natsConfigPath := filepath.Join(configDir, "nats-hub.conf")
	if err := os.WriteFile(natsConfigPath, []byte(natsConfigContent), 0600); err != nil {
		return fmt.Errorf("failed to write nats hub config: %w", err)
	}

	return nil
}

// ConfigureLeaf configures the NATS leaf connection for the manager.
func ConfigureLeaf(cfg *config.Config, credsPath string) error {
	if _, err := os.Stat(credsPath); os.IsNotExist(err) {
		return fmt.Errorf("nats credentials missing at %s", credsPath)
	}
	return nil
}

// LoadAmuxAccountKey loads the Amux Account KeyPair for signing User creds.
func LoadAmuxAccountKey() (nkeys.KeyPair, error) {
	configDir, _ := paths.DefaultConfigDir()
	keyPath := filepath.Join(configDir, "nats", "keys", "amux.nkey")
	return loadKeyPair(keyPath)
}

// --- Internal Helpers ---

func setupNATSAuth(baseDir string) error {
	keysDir := filepath.Join(baseDir, "keys")
	resolverDir := filepath.Join(baseDir, "resolver")
	
	if err := os.MkdirAll(keysDir, 0700); err != nil {
		return err
	}
	if err := os.MkdirAll(resolverDir, 0755); err != nil { // Needs to be readable by server
		return err
	}

	// 1. Operator
	opKP, err := loadOrGenerateKey(filepath.Join(keysDir, "operator.nkey"), nkeys.CreateOperator)
	if err != nil {
		return err
	}
	opPub, _ := opKP.PublicKey()

	// 2. System Account
	sysKP, err := loadOrGenerateKey(filepath.Join(keysDir, "system.nkey"), nkeys.CreateAccount)
	if err != nil {
		return err
	}
	sysPub, _ := sysKP.PublicKey()

	// 3. Amux Account
	amuxKP, err := loadOrGenerateKey(filepath.Join(keysDir, "amux.nkey"), nkeys.CreateAccount)
	if err != nil {
		return err
	}
	amuxPub, _ := amuxKP.PublicKey()

	// 4. Generate/Update Operator JWT
	opClaims := jwt.NewOperatorClaims(opPub)
	opClaims.Name = "AMUX_OP"
	opClaims.Expires = time.Now().Add(10 * 365 * 24 * time.Hour).Unix()
	opClaims.SystemAccount = sysPub
	opJWT, err := opClaims.Encode(opKP)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(baseDir, "operator.jwt"), []byte(opJWT), 0644); err != nil {
		return err
	}

	// 5. Generate/Update System Account JWT
	sysClaims := jwt.NewAccountClaims(sysPub)
	sysClaims.Name = "SYS"
	sysJWT, err := sysClaims.Encode(opKP)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(resolverDir, sysPub+".jwt"), []byte(sysJWT), 0644); err != nil {
		return err
	}

	// 6. Generate/Update Amux Account JWT
	amuxClaims := jwt.NewAccountClaims(amuxPub)
	amuxClaims.Name = "AMUX"
	amuxClaims.Limits.JetStreamLimits = jwt.JetStreamLimits{
		DiskStorage:   -1,
		MemoryStorage: -1,
		Streams:       -1,
		Consumer:      -1,
	}
	amuxJWT, err := amuxClaims.Encode(opKP)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(resolverDir, amuxPub+".jwt"), []byte(amuxJWT), 0644); err != nil {
		return err
	}

	return nil
}

func loadOrGenerateKey(path string, createFn func() (nkeys.KeyPair, error)) (nkeys.KeyPair, error) {
	if _, err := os.Stat(path); err == nil {
		return loadKeyPair(path)
	}
	
	kp, err := createFn()
	if err != nil {
		return nil, err
	}
	
	seed, _ := kp.Seed()
	if err := os.WriteFile(path, seed, 0600); err != nil {
		return nil, err
	}
	
	return kp, nil
}

func loadKeyPair(path string) (nkeys.KeyPair, error) {
	seed, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return nkeys.FromSeed(seed)
}
